// Code generated by protoc-gen-go.
// source: riak.proto
// DO NOT EDIT!

package riak

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type RpbBucketProps_RpbReplMode int32

const (
	RpbBucketProps_false    RpbBucketProps_RpbReplMode = 0
	RpbBucketProps_realtime RpbBucketProps_RpbReplMode = 1
	RpbBucketProps_fullsync RpbBucketProps_RpbReplMode = 2
	RpbBucketProps_true     RpbBucketProps_RpbReplMode = 3
)

var RpbBucketProps_RpbReplMode_name = map[int32]string{
	0: "false",
	1: "realtime",
	2: "fullsync",
	3: "true",
}
var RpbBucketProps_RpbReplMode_value = map[string]int32{
	"false":    0,
	"realtime": 1,
	"fullsync": 2,
	"true":     3,
}

func (x RpbBucketProps_RpbReplMode) Enum() *RpbBucketProps_RpbReplMode {
	p := new(RpbBucketProps_RpbReplMode)
	*p = x
	return p
}
func (x RpbBucketProps_RpbReplMode) String() string {
	return proto.EnumName(RpbBucketProps_RpbReplMode_name, int32(x))
}
func (x RpbBucketProps_RpbReplMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *RpbBucketProps_RpbReplMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RpbBucketProps_RpbReplMode_value, data, "RpbBucketProps_RpbReplMode")
	if err != nil {
		return err
	}
	*x = RpbBucketProps_RpbReplMode(value)
	return nil
}

type RpbErrorResp struct {
	Errmsg           []byte  `protobuf:"bytes,1,req,name=errmsg" json:"errmsg,omitempty"`
	Errcode          *uint32 `protobuf:"varint,2,req,name=errcode" json:"errcode,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *RpbErrorResp) Reset()         { *this = RpbErrorResp{} }
func (this *RpbErrorResp) String() string { return proto.CompactTextString(this) }
func (*RpbErrorResp) ProtoMessage()       {}

func (this *RpbErrorResp) GetErrmsg() []byte {
	if this != nil {
		return this.Errmsg
	}
	return nil
}

func (this *RpbErrorResp) GetErrcode() uint32 {
	if this != nil && this.Errcode != nil {
		return *this.Errcode
	}
	return 0
}

type RpbGetServerInfoResp struct {
	Node             []byte `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
	ServerVersion    []byte `protobuf:"bytes,2,opt,name=server_version" json:"server_version,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RpbGetServerInfoResp) Reset()         { *this = RpbGetServerInfoResp{} }
func (this *RpbGetServerInfoResp) String() string { return proto.CompactTextString(this) }
func (*RpbGetServerInfoResp) ProtoMessage()       {}

func (this *RpbGetServerInfoResp) GetNode() []byte {
	if this != nil {
		return this.Node
	}
	return nil
}

func (this *RpbGetServerInfoResp) GetServerVersion() []byte {
	if this != nil {
		return this.ServerVersion
	}
	return nil
}

type RpbPair struct {
	Key              []byte `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            []byte `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RpbPair) Reset()         { *this = RpbPair{} }
func (this *RpbPair) String() string { return proto.CompactTextString(this) }
func (*RpbPair) ProtoMessage()       {}

func (this *RpbPair) GetKey() []byte {
	if this != nil {
		return this.Key
	}
	return nil
}

func (this *RpbPair) GetValue() []byte {
	if this != nil {
		return this.Value
	}
	return nil
}

type RpbGetBucketReq struct {
	Bucket           []byte `protobuf:"bytes,1,req,name=bucket" json:"bucket,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RpbGetBucketReq) Reset()         { *this = RpbGetBucketReq{} }
func (this *RpbGetBucketReq) String() string { return proto.CompactTextString(this) }
func (*RpbGetBucketReq) ProtoMessage()       {}

func (this *RpbGetBucketReq) GetBucket() []byte {
	if this != nil {
		return this.Bucket
	}
	return nil
}

type RpbGetBucketResp struct {
	Props            *RpbBucketProps `protobuf:"bytes,1,req,name=props" json:"props,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (this *RpbGetBucketResp) Reset()         { *this = RpbGetBucketResp{} }
func (this *RpbGetBucketResp) String() string { return proto.CompactTextString(this) }
func (*RpbGetBucketResp) ProtoMessage()       {}

func (this *RpbGetBucketResp) GetProps() *RpbBucketProps {
	if this != nil {
		return this.Props
	}
	return nil
}

type RpbSetBucketReq struct {
	Bucket           []byte          `protobuf:"bytes,1,req,name=bucket" json:"bucket,omitempty"`
	Props            *RpbBucketProps `protobuf:"bytes,2,req,name=props" json:"props,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (this *RpbSetBucketReq) Reset()         { *this = RpbSetBucketReq{} }
func (this *RpbSetBucketReq) String() string { return proto.CompactTextString(this) }
func (*RpbSetBucketReq) ProtoMessage()       {}

func (this *RpbSetBucketReq) GetBucket() []byte {
	if this != nil {
		return this.Bucket
	}
	return nil
}

func (this *RpbSetBucketReq) GetProps() *RpbBucketProps {
	if this != nil {
		return this.Props
	}
	return nil
}

type RpbModFun struct {
	Module           []byte `protobuf:"bytes,1,req,name=module" json:"module,omitempty"`
	Function         []byte `protobuf:"bytes,2,req,name=function" json:"function,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RpbModFun) Reset()         { *this = RpbModFun{} }
func (this *RpbModFun) String() string { return proto.CompactTextString(this) }
func (*RpbModFun) ProtoMessage()       {}

func (this *RpbModFun) GetModule() []byte {
	if this != nil {
		return this.Module
	}
	return nil
}

func (this *RpbModFun) GetFunction() []byte {
	if this != nil {
		return this.Function
	}
	return nil
}

type RpbCommitHook struct {
	Modfun           *RpbModFun `protobuf:"bytes,1,opt,name=modfun" json:"modfun,omitempty"`
	Name             []byte     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (this *RpbCommitHook) Reset()         { *this = RpbCommitHook{} }
func (this *RpbCommitHook) String() string { return proto.CompactTextString(this) }
func (*RpbCommitHook) ProtoMessage()       {}

func (this *RpbCommitHook) GetModfun() *RpbModFun {
	if this != nil {
		return this.Modfun
	}
	return nil
}

func (this *RpbCommitHook) GetName() []byte {
	if this != nil {
		return this.Name
	}
	return nil
}

type RpbBucketProps struct {
	NVal             *uint32                     `protobuf:"varint,1,opt,name=n_val" json:"n_val,omitempty"`
	AllowMult        *bool                       `protobuf:"varint,2,opt,name=allow_mult" json:"allow_mult,omitempty"`
	LastWriteWins    *bool                       `protobuf:"varint,3,opt,name=last_write_wins" json:"last_write_wins,omitempty"`
	Precommit        []*RpbCommitHook            `protobuf:"bytes,4,rep,name=precommit" json:"precommit,omitempty"`
	HasPrecommit     *bool                       `protobuf:"varint,5,opt,name=has_precommit,def=0" json:"has_precommit,omitempty"`
	Postcommit       []*RpbCommitHook            `protobuf:"bytes,6,rep,name=postcommit" json:"postcommit,omitempty"`
	HasPostcommit    *bool                       `protobuf:"varint,7,opt,name=has_postcommit,def=0" json:"has_postcommit,omitempty"`
	ChashKeyfun      *RpbModFun                  `protobuf:"bytes,8,opt,name=chash_keyfun" json:"chash_keyfun,omitempty"`
	Linkfun          *RpbModFun                  `protobuf:"bytes,9,opt,name=linkfun" json:"linkfun,omitempty"`
	OldVclock        *uint32                     `protobuf:"varint,10,opt,name=old_vclock" json:"old_vclock,omitempty"`
	YoungVclock      *uint32                     `protobuf:"varint,11,opt,name=young_vclock" json:"young_vclock,omitempty"`
	BigVclock        *uint32                     `protobuf:"varint,12,opt,name=big_vclock" json:"big_vclock,omitempty"`
	SmallVclock      *uint32                     `protobuf:"varint,13,opt,name=small_vclock" json:"small_vclock,omitempty"`
	Pr               *uint32                     `protobuf:"varint,14,opt,name=pr" json:"pr,omitempty"`
	R                *uint32                     `protobuf:"varint,15,opt,name=r" json:"r,omitempty"`
	W                *uint32                     `protobuf:"varint,16,opt,name=w" json:"w,omitempty"`
	Pw               *uint32                     `protobuf:"varint,17,opt,name=pw" json:"pw,omitempty"`
	Dw               *uint32                     `protobuf:"varint,18,opt,name=dw" json:"dw,omitempty"`
	Rw               *uint32                     `protobuf:"varint,19,opt,name=rw" json:"rw,omitempty"`
	BasicQuorum      *bool                       `protobuf:"varint,20,opt,name=basic_quorum" json:"basic_quorum,omitempty"`
	NotfoundOk       *bool                       `protobuf:"varint,21,opt,name=notfound_ok" json:"notfound_ok,omitempty"`
	Backend          []byte                      `protobuf:"bytes,22,opt,name=backend" json:"backend,omitempty"`
	Search           *bool                       `protobuf:"varint,23,opt,name=search" json:"search,omitempty"`
	Repl             *RpbBucketProps_RpbReplMode `protobuf:"varint,24,opt,name=repl,enum=RpbBucketProps_RpbReplMode" json:"repl,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (this *RpbBucketProps) Reset()         { *this = RpbBucketProps{} }
func (this *RpbBucketProps) String() string { return proto.CompactTextString(this) }
func (*RpbBucketProps) ProtoMessage()       {}

const Default_RpbBucketProps_HasPrecommit bool = false
const Default_RpbBucketProps_HasPostcommit bool = false

func (this *RpbBucketProps) GetNVal() uint32 {
	if this != nil && this.NVal != nil {
		return *this.NVal
	}
	return 0
}

func (this *RpbBucketProps) GetAllowMult() bool {
	if this != nil && this.AllowMult != nil {
		return *this.AllowMult
	}
	return false
}

func (this *RpbBucketProps) GetLastWriteWins() bool {
	if this != nil && this.LastWriteWins != nil {
		return *this.LastWriteWins
	}
	return false
}

func (this *RpbBucketProps) GetHasPrecommit() bool {
	if this != nil && this.HasPrecommit != nil {
		return *this.HasPrecommit
	}
	return Default_RpbBucketProps_HasPrecommit
}

func (this *RpbBucketProps) GetHasPostcommit() bool {
	if this != nil && this.HasPostcommit != nil {
		return *this.HasPostcommit
	}
	return Default_RpbBucketProps_HasPostcommit
}

func (this *RpbBucketProps) GetChashKeyfun() *RpbModFun {
	if this != nil {
		return this.ChashKeyfun
	}
	return nil
}

func (this *RpbBucketProps) GetLinkfun() *RpbModFun {
	if this != nil {
		return this.Linkfun
	}
	return nil
}

func (this *RpbBucketProps) GetOldVclock() uint32 {
	if this != nil && this.OldVclock != nil {
		return *this.OldVclock
	}
	return 0
}

func (this *RpbBucketProps) GetYoungVclock() uint32 {
	if this != nil && this.YoungVclock != nil {
		return *this.YoungVclock
	}
	return 0
}

func (this *RpbBucketProps) GetBigVclock() uint32 {
	if this != nil && this.BigVclock != nil {
		return *this.BigVclock
	}
	return 0
}

func (this *RpbBucketProps) GetSmallVclock() uint32 {
	if this != nil && this.SmallVclock != nil {
		return *this.SmallVclock
	}
	return 0
}

func (this *RpbBucketProps) GetPr() uint32 {
	if this != nil && this.Pr != nil {
		return *this.Pr
	}
	return 0
}

func (this *RpbBucketProps) GetR() uint32 {
	if this != nil && this.R != nil {
		return *this.R
	}
	return 0
}

func (this *RpbBucketProps) GetW() uint32 {
	if this != nil && this.W != nil {
		return *this.W
	}
	return 0
}

func (this *RpbBucketProps) GetPw() uint32 {
	if this != nil && this.Pw != nil {
		return *this.Pw
	}
	return 0
}

func (this *RpbBucketProps) GetDw() uint32 {
	if this != nil && this.Dw != nil {
		return *this.Dw
	}
	return 0
}

func (this *RpbBucketProps) GetRw() uint32 {
	if this != nil && this.Rw != nil {
		return *this.Rw
	}
	return 0
}

func (this *RpbBucketProps) GetBasicQuorum() bool {
	if this != nil && this.BasicQuorum != nil {
		return *this.BasicQuorum
	}
	return false
}

func (this *RpbBucketProps) GetNotfoundOk() bool {
	if this != nil && this.NotfoundOk != nil {
		return *this.NotfoundOk
	}
	return false
}

func (this *RpbBucketProps) GetBackend() []byte {
	if this != nil {
		return this.Backend
	}
	return nil
}

func (this *RpbBucketProps) GetSearch() bool {
	if this != nil && this.Search != nil {
		return *this.Search
	}
	return false
}

func (this *RpbBucketProps) GetRepl() RpbBucketProps_RpbReplMode {
	if this != nil && this.Repl != nil {
		return *this.Repl
	}
	return 0
}

func init() {
	proto.RegisterEnum("RpbBucketProps_RpbReplMode", RpbBucketProps_RpbReplMode_name, RpbBucketProps_RpbReplMode_value)
}
